# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN apk add --no-cache python3 g++ make \
  && npm install --force && npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy modules and build artifacts
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Default command
CMD ["node", "dist/index.js"]
